baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[module.imports]]
  path = "github.com/willfaught/paige"


[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10


[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40
