baseURL = 'https://7yl4r.github.io/llbigdreams-hugo-paige/'
languageCode = 'en-us'
title = 'Little Laws Big Dreams'
theme = "paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10


[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40

[paige]
  color = "#1E6675" # Bootstrap primary color and theme color for Safari and Windows
  color_scheme = "auto" # Must be "auto", "dark", or "light"
  external_link_new_tab = false # Open external links in new tabs
  math = false # Enable math typesetting
  site_title = "Little Laws Big Dreams" # Appears above the menu, above the site description, if set
  site_description = "" # Appears above the menu, below the site title, if set
  style =  ""
